function [elec, hs, fid] = vt_readpolhemus(data,feedback)
% VT_READPOLHEMUS reads Polhemus data generated by brainstorm and outputs
% an electrode structure, headshape points and fiducial positions in the
% CTF coordinate system. 
% The positions can optionally be plotted (feedback=1).
% The function only works for files containing two estimates of each
% fiducial position.
% Copyright 2016 Mathis Kaiser

if nargin < 2 || isempty(feedback)
    feedback = 0;
end

data = importdata(data, '\t', 1);
nElec=str2double(data.textdata{1,1});

elec.label=data.textdata(2:nElec+1,2); % original labels - might have to be replaced later on
elec.chanpos=data.data(1:nElec,:);
elec.elecpos = elec.chanpos;

hs = data.data(nElec+1:end-6,:); % fiducials at last 6 positions

fid.label = data.textdata(end-2:end,1);
for iPos = 1:3
    fid.pos(iPos,1)=mean(str2double(data.textdata([end-6+iPos end-3+iPos],2)));
    fid.pos(iPos,2:3)=mean(data.data([end-6+iPos end-3+iPos],1:2));
end

if feedback
    figure;
    plot3(elec.chanpos(:,1), elec.chanpos(:,2), elec.chanpos(:,3), 'r*');hold on
    plot3(hs(:,1),hs(:,2),hs(:,3), 'y.');
    plot3(fid.pos(:,1), fid.pos(:,2), fid.pos(:,3), 'go');
    axis square
end
